name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@0.1
      with:
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
         args: "."
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy documentation
      uses: dovecot/rsync-deployments@master
      with:
        RSYNC_OPTIONS: -azr --delete
        RSYNC_TARGET: docs@talvi.dovecot.org:public_html/.
        RSYNC_BASE_DIR: _build/.
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
